---
title: ""
format:
  html:
    theme: 
      light: ember.scss
      dark: slate
    css: custom.scss
    fontsize: 1.2em
    linestretch: 1.7
    smooth-scroll: true 
    linkcolor: "#62259d"
    page-layout: article
  typst:
    papersize: us-letter
    mainfont: "Source Serif Pro"
    fontsize: 14pt
    margin:
      x: 1.25in
      y: 1.25in
fig-responsive: true
embed-resources: false
link-external-icon: false
link-external-newwindow: false
filters: 
  - lightbox
lightbox: auto
editor: visual
---

```{r}
#| label: load-packages
#| include: false

library(tidyverse)
library(palmerpenguins)
```

### Variable Cinema

#### Portable Movies and the Pleasures of Re-Invention

------------------------------------------------------------------------

Society for Cinema Studies Conference, 23 May 2002\
Martin Roberts\
[{{< fa regular envelope >}}](mailto:dokossho@sdf.org) \| [{{< fa brands mastodon >}}](https://merveilles.town/@dokoissho) \| [{{< fa brands github >}}](https://github.com/mroberts1/) \| [{{< fa brands facebook >}}](https://facebook.com/mr05301) \| [{{< fa brands twitter >}}](https://twitter.com/dokoissho)

[Download](index.pdf)

> The introduction of QuickTime in 1991 can be compared to the introduction of the Kinetoscope in 1892: both were used to present short loops, both featured images approximately two by three inches in size, both called for private viewing rather than collective exhibition. The two technologies even appear to play a similar cultural role. If in the early 1890s the public patronized Kinetoscope parlors where peep-hole machines presented them with the latest marvel---tiny, moving photographs arranged in short loops---exactly a hundred years later, computer users were equally fascinated with tiny QuickTime movies that turned a computer into a film projector, however imperfect. Finally, the Lumières' first film screenings of 1895 that shocked their audiences with huge moving images found their parallel in 1995 CD-ROMs in which the moving image finally fills the entire computer screen. ... Thus, exactly a hundred years after cinema was officially 'born,' it was reinvented on a computer screen (Manovich 2000: 313).

Born itself from the loop, cinema in the age of new media seems trapped in its own feedback loop, forever required to re-invent itself at increasingly frequent intervals. Barely a decade after QuickTime's re-invention of motion pictures on the computer screen, indeed, it is being re-invented yet again on the even smaller screens of personal digital assistants (PDAs) such as the PalmPilot, Handspring Visor, or Sony Clié. Tiny, jerky, typically under a minute in duration, today's PDA movies seem to replay in miniature both the history of early cinema and its recent re-invention in DV formats such as QuickTime.

> The history of new media tells us that hardware limitations never go away: they disappear in one area only to come back in another. ... \[W\]e may expect that when digital videos appear on small displays in our cellular phones, personal managers such as Palm Pilot, or other wireless communication devices, they will once again be arranged in short loops because of bandwidth, storage, or CPU limitations (Manovich 2000: 317).

Compared with the technological constraints faced by today's PDA filmmakers, QuickTime looks like IMAX: a screen display of 320 x 320 pixels, limited storage (typical file-sizes are under 1 Mb), a frame-rate of 6 fps (compared to 30 fps for video); until last year, no color; until very recently, no audio---even the accelerated history of PDA movies has barely moved beyond the silent cinema stage. Like the pioneers of early cinema and of QuickTime movies before them, however, PDA moviemakers are finding ingenious solutions to these constraints by tweaking frame-rates, codecs, and screen resolution. Just as in early cinema, montage became an aesthetic solution to the limited length of film reels, or in videogame development looped graphics were a work-around for slow CPU speed or bandwidth, today's PDA moviemakers are devising new aesthetic strategies in response to the limitations facing them, in the process inventing a new visual language for a new medium.

The production of "movies"---itself a problematic term, to which I shall return---for portable media devices is symptomatic of an aspect of contemporary visual culture which has received surprisingly little attention to date. If motion pictures have outgrown even the IMAX screen in recent years, like Alice, they have also been shrinking. While much scholarly attention has focused on the history of large-format cinema (e.g. Belton 1992), less attention has been paid to the miniaturization of cinema and movie-making, from the seat-back displays of in-flight movies to the playback screens of digital camcorders, PDAs, and even cellphones. The technical conditions underlying this process clearly have much to do with the advent of digital media and its ongoing transformation of film production, distribution, and exhibition, but it also entails a larger transformation in the nature of film culture, in areas such as the relationship of audiences to texts, the social dimension of film viewing, and, of course, content. The reflections on PDA movie-making that follow situate it within the larger context of the minaturization of cinema and consider some of its social, cultural, and economic dimensions.

The most immediate problem in speaking about new digital media texts produced for PDAs and similar devices is what to call them. Although magazines devoted to digital film culture continue to refer to "PDA film-making," what is most apparent is the inadequacy of terms such as "cinema," "film," "motion pictures," or even "movies" to describe these new forms of media production. While historically media texts have been identified by their technology of distribution (print, photography, radio, film, videotape), digital interfaces simulate and often combine these in virtual form, and it is by no means clear how we should refer to the digital media texts produced for PDAs and similar portable media devices: while ultimately the principle of moving pictures seems to justify the term "movies," this term arguably still privileges cinema as the primary cultural referent. Like other digital media texts, PDA movies are hybridized, composite texts which combine both still and moving images in multiple formats, with live-action video being only one element among others.

Susan Stewart's work on scale in cultural representation (1993) offers a useful starting-point for thinking about miniature movie-making. Her discussion of the interchangeability of the miniature and the gigantic seems especially relevant to cinema today. While digitization has extended the moving image beyond even the giant IMAX screen to the scale of entire buildings (the NASDAQ building on Times Square), it has also miniaturized it. QuickTime IMAX clips are easily downloaded for viewing on a laptop. Stewart's work on the gigantic and the miniature also illuminates the often perverse relationship between scale and subject-matter in cinema: large-screen cinema, for example, is noteworthy for its predilection not only with appropriately large objects but also inappropriately small ones (*Microcosmos*; an IMAX movie about the bugs that live in your carpet). While PDA movies frequently depict small objects (e.g. ladybugs), they also make interesting places for viewing clips of Godzilla, King Kong, or *Jaws* movies. Size does matter.

All of this seems to suggest that we have now entered the brave new world of mediumless content predicted by Nicholas Negroponte (1995). It is as if cinema had become liquified, flowing seamlessly through broadband networks, across the screens of Swatches and the surfaces of buildings. Clearly, we are not quite there yet, but as the idea of wristwatch cinema suggests, the issue is not so much a technical as an economic one: not can we do it, but can we sell it? The reason why the doctrine of mediumless content is so attractive to media CEOs, after all, is because it offers the promise of a world in which platform-independent media properties reap maximum revenue for their corporate owners. Clearly, again, we are not quite there yet, but neither is it clear that we ever will be: it seems unlikely, for example, that *Titanic* or *Godzilla* will be coming to a PDA screen near you anytime soon, as long as we can watch them as in-flight movies on DVD on a (relatively) giant laptop screen. PDAs in fact provide an interesting place to see how the mantra of mediumless content does not work. While even in their current technologically-challenged form, they might seem to be a perfect platform for short-format media texts---movie trailers, music videos, commercials---in practice this is not the case. While Hollywood now routinely uses the web for movie promotion, I was unable to find any movie trailers in Palm OS format (although admittedly the Windows PocketPC supports a variety of standard DV formats). In addition to trailers in multiple formats, the *Spiderman* website features desktop wallpaper, screensavers, and mp3-player skins, but no movies for handheld devices. This is no doubt related to the relatively recent introduction of color displays and audio capability in such devices, and will change as these capabilities become standardized, but it does show how media content is very much contingent on the dynamic relationship between new media technologies and markets.

Most PDA movie production to date has been the work of new-media artists or digital film-makers, which also explains why they are so often experimental in nature. The major venues for PDA movie projects have been online film festivals or art-museum exhibits, perhaps the most interesting to date being the [Aggressively Boring Film Festival](https://filmthreat.com/uncategorized/the-aggressively-boring-film-fest/), held online in November 2000 and claimed to be "the first film festival for the Palm OS." A collaborative project of The New Venue, a digital film website, and Generic Media, it showcased 69 silent "films" (the organizers' term) specifically designed for display on a PDA (they could also be previewed from a conventional web browser). The festival's most interesting projects were not only those most successful in working within the technological constraints of the medium, but also those designed specifically to be appropriate to the medium itself: one project, for example, called "Your Very Own Personal Audience," consisted simply of a single shot of a small audience from the viewpoint of an imaginary speaker or performer. Looped as a screensaver on an office desktop, it works as an amusing comment either on the cult of celebrity or the egocentrism of its owner. It would make little sense in any other medium. Other projects self-consciously evoked the history of visual culture beyond cinema: a series of "Matchbook Movies," for example, presented a miniature black-and-white slide show of exotic tourist landmarks, commemorating the early twentieth-century practice of displaying miniature photographs on matchbooks. As can be seen from this example, PDA movies reference not only cinema "proper" but also the larger history of visual culture, again raising questions about the accuracy of referring to them as "movies" at all.

One of the most distinctive aspects of PDA movies is the fact that they are designed for viewing on *portable* media devices, no doubt explaining the frequent references to "pocket cinema," "cinema to go," or comparisons to take-out food. Within the limits of available storage (currently 128 Mb in the case of Sony's memory stick), movies can be collected and literally carried around in the user's pocket, as has long been the case with digital music. New compression formats and storage capacities have massively increased the quality of digital music one can carry around in recent years, of course, and similar developments can be anticipated for digital movies. The portability and collectability of PDA movies lends them an affinity with other forms of collectable media such as trading cards, and introduces the additional dimension of exchange. While the Internet serves as the backbone for such practices of collecting and exchange, a key factor in these developments is wireless technology. One of the most appealing capabilities of PDAs, indeed, is wireless data transfer, popularly known as "beaming," immortalized in the TV commercial in which a woman in a departing train beams her cell number to a hot guy in an adjacent train just before the two trains pull out of the station. Not just cellphone numbers but movies can now be beamed from one PDA to another. If today's children and teenagers trade Pokemon cards and Beanie Babies, mp3 songs and cellphone ringtones, portable movies for PDAs and similar handheld devices look set to become the animated trading-cards of the coming century. 

Miniatures, as Susan Stewart has noted, are closely related to the souvenir, souvenirs themselves often being miniatures. As miniature media texts, PDA movies provide an interesting example of the relationship Stewart mentions between miniaturization and collecting. Stewart's discussion of souvenirs and collecting also illuminates the social dimension of PDA moviemaking. On the Internet, an instant community of PDA filmmakers has sprung up, swapping movies and production tips on websites. 

Several months ago, I attended an opening at the Dia Center for the Arts in New York City for a PDA-based project of new-media artist James Buckhouse in collaboration with dancer Holly Bruback. Titled simply "[Tap](https://www.diaart.org/program/artistswebprojects/james-buckhouse-in-collaboration-with-holly-brubachtap-web-project)," the project featured a number of "beaming stations" from which PDA owners were invited to download motion-capture animations of a male and female tap dancer. Five additional beaming stations were available in public locations around Manhattan for similar use. Once downloaded, the animated figures could be controlled by tapping the PDA screen with a stylus in the usual way, lending the notion of "tap-dancing" a peculiarly literal dimension: they could be required to "practice" various dance steps, and these steps combined into original sequences which could be saved or exchanged by different players. Not being a PDA owner at that time, I consoled myself by playing ethnographic observer to the social behavior of those who did in their interactions with the beaming stations and, more particularly, each other, as groups of people stood around diligently tapping their PDA screens to beam one another the pair of tiny tap-dancing figures. What struck me was how their evident pleasure in the work seemed to derive less from manipulating the animations themselves---obviously a less gregarious and more time-consuming activity---than simply from the technological ritual of beaming itself, with the frisson of participating in the future which it implied. I am reminded here of James Carey's seminal essay (1988) on the "History of the Future" and his notion of the future as a ritual of participation. The social imperative to own new media technologies, and the cultural capital acquired by doing so, can clearly be read as a case in point, but what should be added is how these technologies reconfigure social relations and create new forms of symbolic exchange. 

If PDAs lend themselves well to rituals of collective viewing and exchange, as their audiovisual playback and storage capabilities continue to improve they may also play an important role as a platform for personal media, especially among today's increasingly extended family. To the production of PDA movies by the media industries and by digital artists and filmmakers, indeed, we need to add the popular production of PDA home movies. In this context, PDAs are part of the larger picture of the professionalization of everyday life by new media technologies. It is becoming increasingly routine today to produce and distribute DV recordings of personal events and experiences: weddings, the birth of a child, a family vacation. A DV sequence can be imported from a camcorder onto a PC for processing, then uploaded to the web for distribution or exported to a handheld device used as a digital photo or video album. The current generation of PDAs with built-in digital cameras and mp3 players offer enhanced possibilities for p2p distribution of personal media.

In conclusion, two brief comments, on variability and ephemerality. PDA movies, in the first place, exemplify the variability which Lev Manovich identifies as one of the defining characteristics of the new media object. A key dimension of variability is variability of scale: a Photoshop image or QuickTime movie can be scaled either up or down at variable resolutions, from thumbnail to billboard. The process does not have to stop there, however. Manovich's own [Little Movies](http://variants.artbase.rhizome.org/Q4333/menu3.html) project reduces one of the Lumière brothers' *actualité* films to the dimensions of a single pixel, but there is no reason why the pixel has to be the final frontier of miniaturization. Contemporary artists are already drawing on microchips and producing sculptures in the eye of a needle (Sandaljian 1996), suggesting at least the possibility of a future microcinema. Utopian speculations aside, however, what I want to suggest here is that digital media technologies today are literally introducing a new dimension into cinema, creating little-known forms of cinema-object which may not be recognized as "cinema" at all.

One example of what I have in mind here is what might be called **hypercinema**, a cinema situated within the hyperspace of computer networks and architectures. Historical prototypes here of course include Disney's *Tron* and the *Lawnmover Man* films, with contemporary examples including *The Matrix*, *ExistenZ*, *The Cell*, and so on. A striking recent example is [Warriors of the Net](https://youtu.be/PBWhzz_Gn10) (2002), an animated educational documentary which explains how email works.

::: column-margin
<br /> <br /> <br /> {{< video https://youtu.be/PBWhzz_Gn10 width="320" height="180" >}}
:::

A second example of emerging new dimensions in movie-making is **fractal cinema**. As is well known, variability of scale is one of the characteristic properties of fractal images, in the sense that one can zoom in or out of them to an infinite degree (Gleick 1987). Digital imaging facilitates this process, of course, and numerous websites provide Java applets which enable the viewer to generate and explore such images. It is also possible to capture a particular zoom as a QuickTime movie, thus creating a fractal movie (Godfrey Reggio's recent film *Naqoyqatsi* (2002), the third in the documentary trilogy which includes *Koyanisqaatsi* and *Powaqaatsi*, includes one such fractal "fly-through" sequence). Fractal movies, then, introduce a vertical dimension into the horizontality of cinema, in which a zoom within a single image opens up a new kind of cinematic space. 

A third example, again taking place at the microscopic level, is animated modeling of nanotechnology, or what might be called **nanocinema**: animations of possible or even actual nanotech robots, molecules, etc. None of these examples are coming anytime soon to a multiplex near you, although any of them can be found quite easily on the web. They suggest, however, that the impact of digital technologies on cinema is more than just a matter of *Toy Story* or *Star Wars* sequels, but requires us to rethink what we mean by the concept of "cinema" itself.

The defining principle of each of these examples is animation rather than live action, supporting Manovich's definition of digital cinema as animation in which live action is only one of a range of possible options. Secondly, it should be noted, these new forms of cinema are a cinema of simulation rather than of representation, in the sense that they *model* processes and objects inaccessible to unmediated vision, rather than merely reproducing the real: a cinema of invisibility, then. One thinks here of Benjamin's concept of the optical unconscious and the role of visual media in capturing reality---galloping horses, the wing movements of hummingbirds---otherwise beyond the capabilities of the human eye. The cinematic forms I have described here, however, occupy an imaginary realm of simulation rather than representation which we might better describe as a **digital unconscious**.

------------------------------------------------------------------------

**References**\
Belton, John. 1992. *Widescreen Cinema*. Cambridge, Mass.: Harvard University Press.\
Carey, James W., with John J. Quirk. 1988. "The History of the Future." In *Communication as Culture: Essays on Media and Society*. Boston: Unwyn Hyman: 173-200.\
Gleick, James. 1987. *Chaos: Making a New Science*. New York: Viking.\
Manovich, Lev. 2000. *The Language of New Media*. Cambridge, Mass.: MIT Press.\
Negroponte, Nicholas. 1995. *Being Digital*. New York: Vintage Books.\
Sandaljian, Hagop. 1996. *The Eye of the Needle: The Unique World of Microminiatures of Hagop Sandaljian*. Essay by Ralph Rugoff. Los Angeles: Museum of Jurassic Technology.\
Stewart, Susan. 1993 \[1984\]. *On Longing: Narratives of the Miniature, the Gigantic, the Souvenir, the Collection*. Durham: Duke University Press.

**Web**\
James Bruckhouse and Holly Bruback, [*Tap*](https://www.diaart.org/program/artistswebprojects/james-buckhouse-in-collaboration-with-holly-brubachtap-web-project) (2002)\
Lev Manovich, "[Little Movies](http://manovich.net/index.php/exhibitions/little-movies-rhizome)" (1994-97)\
[*Warriors of the Net*](http://www.warriorsofthe.net) (2002)

------------------------------------------------------------------------
